plugins {
    id 'net.neoforged.moddev'
}

group = project.mod_group_id
version = project.mod_version

repositories {
    maven { name = 'Create'; url = 'https://maven.createmod.net' }
    maven { name = 'NeoForge'; url = 'https://maven.neoforged.net/releases' }
}

base {
    archivesName = project.mod_id
}

neoForge {
    version = project.neoforge_version

    parchment {
        mappingsVersion = '2024.11.17'
        minecraftVersion = project.minecraft_version
    }

    runs {
        client {
            client()
            systemProperty 'neoforge.enabledGameTestNamespaces', project.mod_id
        }
        server {
            server()
            programArgument '--nogui'
            systemProperty 'neoforge.enabledGameTestNamespaces', project.mod_id
        }
        gameTestServer {
            type = 'gameTestServer'
            systemProperty 'neoforge.enabledGameTestNamespaces', project.mod_id
        }
        data {
            data()
            programArguments.addAll '--mod', project.mod_id, '--all', '--output', file('src/generated/resources/'), '--existing', file('src/main/resources/')
        }
    }

    mods {
        "${project.mod_id}" {
            sourceSet(sourceSets.main)
        }
    }
}

dependencies {
    implementation("com.simibubi.create:create-${project.minecraft_version}:${project.create_version}:slim") {
        transitive = false
    }
}

sourceSets.main.resources.srcDir 'src/generated/resources'

processResources {
    var replaceProperties = [
        minecraft_version      : minecraft_version,
        minecraft_version_range: minecraft_version_range,
        neoforge_version       : neoforge_version,
        neoforge_version_range : neoforge_version_range,
        loader_version_range   : loader_version_range,
        mod_id                 : mod_id,
        mod_name               : mod_name,
        mod_license            : mod_license,
        mod_version            : mod_version,
        mod_authors            : mod_authors,
        mod_description       : mod_description
    ]

    inputs.properties replaceProperties
    filesMatching(['META-INF/neoforge.mods.toml']) {
        expand replaceProperties
    }
}

java.toolchain.languageVersion = JavaLanguageVersion.of(21)
